sudo: false
language: node_js
node_js: 7
script:
- travis-lint .travis.yml
- make eslint
cache:
  directories:
  - node_modules
env:
- NODE_ENV=production
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: YZ8VmpkpMlfV5ZWHwcZ8rmRzkjx65ZQBwCNOQJIehamHPqpq+PanHaym22Lbf0oXd0ilRYGr6bNE4bLwR+7/uQMQSuNJLpzingXrXe+hNA6nh8SQGbCG80CPggac6y6CArdfHT1MlKihR6wiSM+TwfKADmhS+uGvahL7pkHGqK03xFpp22F4+KjOr1P6HlMN3MgQp6neKM5qKMejFqKs1Dg/1r71WW9V4RkyEgtF+P3cz4IYpKoa8SkBQ+KDLRZOJdSyhar87SqDEJ8gzH4/k1QoOc3nx7fsA030HsR1cTlE/qOzRDINnoaBu1N34nQBgjozZa373YcG/8S6N60tskKsJBWF5eT33cmzWcofc+jOtNNDtv7rp44zEXi48dluGfRNsumGFZYpExS8K/zcwQVAX++lAryo3lOl1lmTfYkQyr/y/6LJx2cfx9fObWrvwIJePZnf1Myf2VryQ5UELRb6VeyDq0jimPwfD3IVIRdZO9Cxq9WS3mr2W+QLVOt8Wo93kzp7mANeIWx4xF9zsMtoc9cTSq90xxQF+6+0Te2YQ+NpKlYziU+4VWhh/rYUIzm3c4Ro+aVYpe1bc4bjlh6MsRgcwQZqwESGq/SPx3Q3xJO3ytoxyLmmkncQnrHeGwnbqZB37KpHWOTftJcmqYM+r35+799xe83bdYyt0mY=
  app:
    secure: JjMtFiydCDhMxmP1yez6P8y6AbB/6cXOQ/LoMAPxayH5h3F7eZhrJj6s+ekrpomV9q6jqAZeN0bJDqtfj33nY9t9iusUKz+um7WyGeR9GFppu+6OAMGrAsShrCEGgNd4AkBorCj+VK5O0w3egoKtN8wOjMk0oVeasbfo3Pd2OAlDACsdViT5N3V6WiBLCIdHfYFPPB3hdNTW7l3qzPZbuE83LJMa9fPiMSGslfzgQ/1+L2SGiCUrFzmEB0n8T90wWy67UXjjYhG06Vh5mC8N46PcV50r6sfldaDP9OGiWMdPmV0E6RXTIhcNkHJUOHUZlwRMJxuKMvphXbyK66ebseZP/95xAwOz5oWBVSP52+RvHpwZY4HHXcURQmNmKGtFerVKFj5UWLkJLlPln3kClQIDF6MEla1B07DZuBGYybN4hObI6HxULwhViNrWbXEATjalzDRf4p/fAx30GO5zEBcAHnB8NH4SMZ/d6nz7nvD5myeroTUaH38Ltu+SrwkFOGkWocw7eV1sjN8H3pvbvfhp4XX2HwebQpeGcViTIj7Eu2CworiOhhZxyMoWwcOFh/T/K0+cOPOdgyCVV3uR9JePnDB+OnZSQg9Cbf7YRMk5y+M/FhdQdNOdcpmpuTXq6n7QlFUiWtHCNR0yW2kqd7GcTVjiOOB1EgBJjLHFCcY=
